import logging
import os
from pathlib import Path

from fpdf import FPDF
from datetime import datetime

from services.zia_service import translate_text

logger = logging.getLogger("PdfService")

# fpdf2's built-in "Arial"/"helvetica" is a Latin-1 font — any character outside
# that range (Kannada/Devanagari script, curly quotes, rupee sign, emoji, ...)
# raised a hard FPDFException and turned report generation into a 500. This is a
# trilingual (English+Hindi+Kannada) product whose chat transcripts and case
# text can genuinely contain either script at any time, so this wasn't an edge
# case, it was a guaranteed crash the moment someone exported a Kannada- or
# Hindi-containing conversation. Fixed by registering Noto Sans (broad Unicode/
# Latin coverage) as the base font with Noto Sans Kannada and Noto Sans
# Devanagari as automatic per-glyph fallbacks (fpdf2's set_fallback_fonts) —
# live-verified this renders real Kannada glyphs, not tofu boxes, and characters
# missing from all three fonts (e.g. rare pictographic symbols) are silently
# skipped instead of raising. NotoSansDevanagari.ttf (OFL-licensed, same family
# as the other two) was added once chat's language-override feature made it
# possible for a Hindi-translated answer to actually reach a PDF export —
# previously ChatHistory only ever stored English text, so this gap existed
# but was never triggered.
_FONTS_DIR = Path(__file__).resolve().parent.parent / "assets" / "fonts"


def _new_pdf() -> FPDF:
    pdf = FPDF()
    pdf.add_page()
    # No separate bold/italic TTFs are bundled — registering the same regular
    # face under the B/I style slots avoids fpdf2 falling back to core "Arial"
    # (and losing Unicode support) the moment set_font(..., "B"/"I") is called.
    regular = str(_FONTS_DIR / "NotoSans.ttf")
    pdf.add_font("NotoSans", "", regular)
    pdf.add_font("NotoSans", "B", regular)
    pdf.add_font("NotoSans", "I", regular)
    pdf.add_font("NotoSansKannada", "", str(_FONTS_DIR / "NotoSansKannada.ttf"))
    pdf.add_font("NotoSansDevanagari", "", str(_FONTS_DIR / "NotoSansDevanagari.ttf"))
    pdf.set_fallback_fonts(["NotoSansKannada", "NotoSansDevanagari"])
    return pdf


def generate_case_report(crime_no: str, content: str, author: str) -> str:
    pdf = _new_pdf()

    # Header / Title
    pdf.set_font("NotoSans", 'B', 16)
    pdf.cell(200, 10, txt=f"Official Case Report: {crime_no}", ln=True, align='C')

    # Metadata (Date & Author)
    pdf.set_font("NotoSans", 'I', 10)
    current_time = datetime.now().strftime("%d-%m-%Y %H:%M:%S")
    pdf.cell(200, 10, txt=f"Generated by: {author} | Date: {current_time}", ln=True, align='C')

    pdf.ln(10)

    # Main Content (Report body) — multi_cell text ko automatically next line mein wrap kar deta hai
    pdf.set_font("NotoSans", size=12)
    pdf.multi_cell(0, 10, txt=content)

    os.makedirs("temp_reports", exist_ok=True)
    file_path = f"temp_reports/Report_{crime_no}.pdf"
    pdf.output(file_path)

    return file_path


_LANGUAGE_LABELS = {"hi": "Hindi", "kn": "Kannada"}


def generate_conversation_report(session_id: str, messages: list, target_language: str | None = None) -> str:
    """target_language ("hi"/"kn", or None/"en" for no translation) renders
    ASSISTANT messages in that language instead of the English text
    ChatHistory actually stores — the sticky language-override preference,
    when a conversation has one (see api/routers/report.py). User messages
    are left exactly as typed; this is about the assistant's replies, not
    rewriting what the officer themselves said. Translated per-message at
    export time rather than storing translated text in ChatHistory itself —
    keeps the stored record (and everything that reads it back into a
    prompt — history-based follow-up resolution, the eval harness's keyword
    checks) as the single English canonical version, always.

    A single message's translation failing (the same live Zia flakiness
    documented throughout this project) falls back to that one message's
    English text with an inline note, rather than failing the whole export —
    an officer exporting a 20-turn conversation shouldn't lose the entire
    PDF because turn 14's translation call happened to time out."""
    pdf = _new_pdf()

    pdf.set_font("NotoSans", 'B', 16)
    pdf.cell(200, 10, txt="Chat Conversation Log", ln=True, align='C')

    pdf.set_font("NotoSans", 'I', 10)
    current_time = datetime.now().strftime("%d-%m-%Y %H:%M:%S")
    pdf.cell(200, 10, txt=f"Session: {session_id} | Exported: {current_time}", ln=True, align='C')
    if target_language in _LANGUAGE_LABELS:
        pdf.cell(200, 8, txt=f"Assistant replies translated to {_LANGUAGE_LABELS[target_language]}", ln=True, align='C')

    pdf.ln(10)

    for msg in messages:
        role = msg.get("Role", "unknown")
        text = msg.get("Message", "")
        sent_at = msg.get("SetAt", "")

        if role == "assistant" and target_language in _LANGUAGE_LABELS and text.strip():
            try:
                text = translate_text(text, "en", target_language)
            except Exception as e:
                logger.warning(f"Conversation-export translation failed for one message, showing English: {e}")
                text = f"{text}\n[Translation to {_LANGUAGE_LABELS[target_language]} unavailable for this message]"

        # fpdf2 quirk: multi_cell(width=0) computes available width from the
        # current x position, which a prior multi_cell call can leave stuck away
        # from the left margin — explicitly resetting x avoids a spurious
        # "Not enough horizontal space" exception on the next call.
        pdf.set_x(pdf.l_margin)
        pdf.set_font("NotoSans", 'B', 11)
        pdf.multi_cell(0, 8, txt=f"[{sent_at}] {role.upper()}:")
        pdf.set_x(pdf.l_margin)
        pdf.set_font("NotoSans", size=11)
        pdf.multi_cell(0, 8, txt=text)
        pdf.ln(3)

    os.makedirs("temp_reports", exist_ok=True)
    file_path = f"temp_reports/Conversation_{session_id}.pdf"
    pdf.output(file_path)

    return file_path
